# Generated by Django 4.2.1 on 2023-06-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='ссылка'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=30, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='up_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название товара в верхнем регистре'),
        ),
    ]
